# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/honza/Paradise/SymDivine_Vojta

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/honza/Paradise/SymDivine_Vojta

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/Paradise/SymDivine_Vojta/CMakeFiles /home/honza/Paradise/SymDivine_Vojta/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/Paradise/SymDivine_Vojta/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named symdivine

# Build rule for target.
symdivine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symdivine
.PHONY : symdivine

# fast build rule for target.
symdivine/fast:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/build
.PHONY : symdivine/fast

libs/docopt/docopt.o: libs/docopt/docopt.cpp.o
.PHONY : libs/docopt/docopt.o

# target to build an object file
libs/docopt/docopt.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/libs/docopt/docopt.cpp.o
.PHONY : libs/docopt/docopt.cpp.o

libs/docopt/docopt.i: libs/docopt/docopt.cpp.i
.PHONY : libs/docopt/docopt.i

# target to preprocess a source file
libs/docopt/docopt.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/libs/docopt/docopt.cpp.i
.PHONY : libs/docopt/docopt.cpp.i

libs/docopt/docopt.s: libs/docopt/docopt.cpp.s
.PHONY : libs/docopt/docopt.s

# target to generate assembly for a file
libs/docopt/docopt.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/libs/docopt/docopt.cpp.s
.PHONY : libs/docopt/docopt.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/parser.cpp.s
.PHONY : parser.cpp.s

src/llvmsym/datastore.o: src/llvmsym/datastore.cpp.o
.PHONY : src/llvmsym/datastore.o

# target to build an object file
src/llvmsym/datastore.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/datastore.cpp.o
.PHONY : src/llvmsym/datastore.cpp.o

src/llvmsym/datastore.i: src/llvmsym/datastore.cpp.i
.PHONY : src/llvmsym/datastore.i

# target to preprocess a source file
src/llvmsym/datastore.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/datastore.cpp.i
.PHONY : src/llvmsym/datastore.cpp.i

src/llvmsym/datastore.s: src/llvmsym/datastore.cpp.s
.PHONY : src/llvmsym/datastore.s

# target to generate assembly for a file
src/llvmsym/datastore.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/datastore.cpp.s
.PHONY : src/llvmsym/datastore.cpp.s

src/llvmsym/emptydatastore.o: src/llvmsym/emptydatastore.cpp.o
.PHONY : src/llvmsym/emptydatastore.o

# target to build an object file
src/llvmsym/emptydatastore.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/emptydatastore.cpp.o
.PHONY : src/llvmsym/emptydatastore.cpp.o

src/llvmsym/emptydatastore.i: src/llvmsym/emptydatastore.cpp.i
.PHONY : src/llvmsym/emptydatastore.i

# target to preprocess a source file
src/llvmsym/emptydatastore.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/emptydatastore.cpp.i
.PHONY : src/llvmsym/emptydatastore.cpp.i

src/llvmsym/emptydatastore.s: src/llvmsym/emptydatastore.cpp.s
.PHONY : src/llvmsym/emptydatastore.s

# target to generate assembly for a file
src/llvmsym/emptydatastore.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/emptydatastore.cpp.s
.PHONY : src/llvmsym/emptydatastore.cpp.s

src/llvmsym/error.o: src/llvmsym/error.cpp.o
.PHONY : src/llvmsym/error.o

# target to build an object file
src/llvmsym/error.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/error.cpp.o
.PHONY : src/llvmsym/error.cpp.o

src/llvmsym/error.i: src/llvmsym/error.cpp.i
.PHONY : src/llvmsym/error.i

# target to preprocess a source file
src/llvmsym/error.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/error.cpp.i
.PHONY : src/llvmsym/error.cpp.i

src/llvmsym/error.s: src/llvmsym/error.cpp.s
.PHONY : src/llvmsym/error.s

# target to generate assembly for a file
src/llvmsym/error.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/error.cpp.s
.PHONY : src/llvmsym/error.cpp.s

src/llvmsym/formula/rpn.o: src/llvmsym/formula/rpn.cpp.o
.PHONY : src/llvmsym/formula/rpn.o

# target to build an object file
src/llvmsym/formula/rpn.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/rpn.cpp.o
.PHONY : src/llvmsym/formula/rpn.cpp.o

src/llvmsym/formula/rpn.i: src/llvmsym/formula/rpn.cpp.i
.PHONY : src/llvmsym/formula/rpn.i

# target to preprocess a source file
src/llvmsym/formula/rpn.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/rpn.cpp.i
.PHONY : src/llvmsym/formula/rpn.cpp.i

src/llvmsym/formula/rpn.s: src/llvmsym/formula/rpn.cpp.s
.PHONY : src/llvmsym/formula/rpn.s

# target to generate assembly for a file
src/llvmsym/formula/rpn.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/rpn.cpp.s
.PHONY : src/llvmsym/formula/rpn.cpp.s

src/llvmsym/formula/z3.o: src/llvmsym/formula/z3.cpp.o
.PHONY : src/llvmsym/formula/z3.o

# target to build an object file
src/llvmsym/formula/z3.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/z3.cpp.o
.PHONY : src/llvmsym/formula/z3.cpp.o

src/llvmsym/formula/z3.i: src/llvmsym/formula/z3.cpp.i
.PHONY : src/llvmsym/formula/z3.i

# target to preprocess a source file
src/llvmsym/formula/z3.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/z3.cpp.i
.PHONY : src/llvmsym/formula/z3.cpp.i

src/llvmsym/formula/z3.s: src/llvmsym/formula/z3.cpp.s
.PHONY : src/llvmsym/formula/z3.s

# target to generate assembly for a file
src/llvmsym/formula/z3.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/formula/z3.cpp.s
.PHONY : src/llvmsym/formula/z3.cpp.s

src/llvmsym/llvmdata.o: src/llvmsym/llvmdata.cpp.o
.PHONY : src/llvmsym/llvmdata.o

# target to build an object file
src/llvmsym/llvmdata.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/llvmdata.cpp.o
.PHONY : src/llvmsym/llvmdata.cpp.o

src/llvmsym/llvmdata.i: src/llvmsym/llvmdata.cpp.i
.PHONY : src/llvmsym/llvmdata.i

# target to preprocess a source file
src/llvmsym/llvmdata.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/llvmdata.cpp.i
.PHONY : src/llvmsym/llvmdata.cpp.i

src/llvmsym/llvmdata.s: src/llvmsym/llvmdata.cpp.s
.PHONY : src/llvmsym/llvmdata.s

# target to generate assembly for a file
src/llvmsym/llvmdata.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/llvmdata.cpp.s
.PHONY : src/llvmsym/llvmdata.cpp.s

src/llvmsym/memorylayout.o: src/llvmsym/memorylayout.cpp.o
.PHONY : src/llvmsym/memorylayout.o

# target to build an object file
src/llvmsym/memorylayout.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/memorylayout.cpp.o
.PHONY : src/llvmsym/memorylayout.cpp.o

src/llvmsym/memorylayout.i: src/llvmsym/memorylayout.cpp.i
.PHONY : src/llvmsym/memorylayout.i

# target to preprocess a source file
src/llvmsym/memorylayout.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/memorylayout.cpp.i
.PHONY : src/llvmsym/memorylayout.cpp.i

src/llvmsym/memorylayout.s: src/llvmsym/memorylayout.cpp.s
.PHONY : src/llvmsym/memorylayout.s

# target to generate assembly for a file
src/llvmsym/memorylayout.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/memorylayout.cpp.s
.PHONY : src/llvmsym/memorylayout.cpp.s

src/llvmsym/programutils/config.o: src/llvmsym/programutils/config.cpp.o
.PHONY : src/llvmsym/programutils/config.o

# target to build an object file
src/llvmsym/programutils/config.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/config.cpp.o
.PHONY : src/llvmsym/programutils/config.cpp.o

src/llvmsym/programutils/config.i: src/llvmsym/programutils/config.cpp.i
.PHONY : src/llvmsym/programutils/config.i

# target to preprocess a source file
src/llvmsym/programutils/config.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/config.cpp.i
.PHONY : src/llvmsym/programutils/config.cpp.i

src/llvmsym/programutils/config.s: src/llvmsym/programutils/config.cpp.s
.PHONY : src/llvmsym/programutils/config.s

# target to generate assembly for a file
src/llvmsym/programutils/config.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/config.cpp.s
.PHONY : src/llvmsym/programutils/config.cpp.s

src/llvmsym/programutils/statistics.o: src/llvmsym/programutils/statistics.cpp.o
.PHONY : src/llvmsym/programutils/statistics.o

# target to build an object file
src/llvmsym/programutils/statistics.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/statistics.cpp.o
.PHONY : src/llvmsym/programutils/statistics.cpp.o

src/llvmsym/programutils/statistics.i: src/llvmsym/programutils/statistics.cpp.i
.PHONY : src/llvmsym/programutils/statistics.i

# target to preprocess a source file
src/llvmsym/programutils/statistics.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/statistics.cpp.i
.PHONY : src/llvmsym/programutils/statistics.cpp.i

src/llvmsym/programutils/statistics.s: src/llvmsym/programutils/statistics.cpp.s
.PHONY : src/llvmsym/programutils/statistics.s

# target to generate assembly for a file
src/llvmsym/programutils/statistics.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/programutils/statistics.cpp.s
.PHONY : src/llvmsym/programutils/statistics.cpp.s

src/llvmsym/smtdatastore.o: src/llvmsym/smtdatastore.cpp.o
.PHONY : src/llvmsym/smtdatastore.o

# target to build an object file
src/llvmsym/smtdatastore.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore.cpp.o
.PHONY : src/llvmsym/smtdatastore.cpp.o

src/llvmsym/smtdatastore.i: src/llvmsym/smtdatastore.cpp.i
.PHONY : src/llvmsym/smtdatastore.i

# target to preprocess a source file
src/llvmsym/smtdatastore.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore.cpp.i
.PHONY : src/llvmsym/smtdatastore.cpp.i

src/llvmsym/smtdatastore.s: src/llvmsym/smtdatastore.cpp.s
.PHONY : src/llvmsym/smtdatastore.s

# target to generate assembly for a file
src/llvmsym/smtdatastore.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore.cpp.s
.PHONY : src/llvmsym/smtdatastore.cpp.s

src/llvmsym/smtdatastore_partial.o: src/llvmsym/smtdatastore_partial.cpp.o
.PHONY : src/llvmsym/smtdatastore_partial.o

# target to build an object file
src/llvmsym/smtdatastore_partial.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore_partial.cpp.o
.PHONY : src/llvmsym/smtdatastore_partial.cpp.o

src/llvmsym/smtdatastore_partial.i: src/llvmsym/smtdatastore_partial.cpp.i
.PHONY : src/llvmsym/smtdatastore_partial.i

# target to preprocess a source file
src/llvmsym/smtdatastore_partial.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore_partial.cpp.i
.PHONY : src/llvmsym/smtdatastore_partial.cpp.i

src/llvmsym/smtdatastore_partial.s: src/llvmsym/smtdatastore_partial.cpp.s
.PHONY : src/llvmsym/smtdatastore_partial.s

# target to generate assembly for a file
src/llvmsym/smtdatastore_partial.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/smtdatastore_partial.cpp.s
.PHONY : src/llvmsym/smtdatastore_partial.cpp.s

src/llvmsym/stanalysis/inputvariables.o: src/llvmsym/stanalysis/inputvariables.cpp.o
.PHONY : src/llvmsym/stanalysis/inputvariables.o

# target to build an object file
src/llvmsym/stanalysis/inputvariables.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/stanalysis/inputvariables.cpp.o
.PHONY : src/llvmsym/stanalysis/inputvariables.cpp.o

src/llvmsym/stanalysis/inputvariables.i: src/llvmsym/stanalysis/inputvariables.cpp.i
.PHONY : src/llvmsym/stanalysis/inputvariables.i

# target to preprocess a source file
src/llvmsym/stanalysis/inputvariables.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/stanalysis/inputvariables.cpp.i
.PHONY : src/llvmsym/stanalysis/inputvariables.cpp.i

src/llvmsym/stanalysis/inputvariables.s: src/llvmsym/stanalysis/inputvariables.cpp.s
.PHONY : src/llvmsym/stanalysis/inputvariables.s

# target to generate assembly for a file
src/llvmsym/stanalysis/inputvariables.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/stanalysis/inputvariables.cpp.s
.PHONY : src/llvmsym/stanalysis/inputvariables.cpp.s

src/llvmsym/thread.o: src/llvmsym/thread.cpp.o
.PHONY : src/llvmsym/thread.o

# target to build an object file
src/llvmsym/thread.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/thread.cpp.o
.PHONY : src/llvmsym/thread.cpp.o

src/llvmsym/thread.i: src/llvmsym/thread.cpp.i
.PHONY : src/llvmsym/thread.i

# target to preprocess a source file
src/llvmsym/thread.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/thread.cpp.i
.PHONY : src/llvmsym/thread.cpp.i

src/llvmsym/thread.s: src/llvmsym/thread.cpp.s
.PHONY : src/llvmsym/thread.s

# target to generate assembly for a file
src/llvmsym/thread.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/llvmsym/thread.cpp.s
.PHONY : src/llvmsym/thread.cpp.s

src/symdivine.o: src/symdivine.cpp.o
.PHONY : src/symdivine.o

# target to build an object file
src/symdivine.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/symdivine.cpp.o
.PHONY : src/symdivine.cpp.o

src/symdivine.i: src/symdivine.cpp.i
.PHONY : src/symdivine.i

# target to preprocess a source file
src/symdivine.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/symdivine.cpp.i
.PHONY : src/symdivine.cpp.i

src/symdivine.s: src/symdivine.cpp.s
.PHONY : src/symdivine.s

# target to generate assembly for a file
src/symdivine.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/symdivine.cpp.s
.PHONY : src/symdivine.cpp.s

src/toolkit/ltl2ba.o: src/toolkit/ltl2ba.cpp.o
.PHONY : src/toolkit/ltl2ba.o

# target to build an object file
src/toolkit/ltl2ba.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/ltl2ba.cpp.o
.PHONY : src/toolkit/ltl2ba.cpp.o

src/toolkit/ltl2ba.i: src/toolkit/ltl2ba.cpp.i
.PHONY : src/toolkit/ltl2ba.i

# target to preprocess a source file
src/toolkit/ltl2ba.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/ltl2ba.cpp.i
.PHONY : src/toolkit/ltl2ba.cpp.i

src/toolkit/ltl2ba.s: src/toolkit/ltl2ba.cpp.s
.PHONY : src/toolkit/ltl2ba.s

# target to generate assembly for a file
src/toolkit/ltl2ba.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/ltl2ba.cpp.s
.PHONY : src/toolkit/ltl2ba.cpp.s

src/toolkit/query_cache.o: src/toolkit/query_cache.cpp.o
.PHONY : src/toolkit/query_cache.o

# target to build an object file
src/toolkit/query_cache.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/query_cache.cpp.o
.PHONY : src/toolkit/query_cache.cpp.o

src/toolkit/query_cache.i: src/toolkit/query_cache.cpp.i
.PHONY : src/toolkit/query_cache.i

# target to preprocess a source file
src/toolkit/query_cache.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/query_cache.cpp.i
.PHONY : src/toolkit/query_cache.cpp.i

src/toolkit/query_cache.s: src/toolkit/query_cache.cpp.s
.PHONY : src/toolkit/query_cache.s

# target to generate assembly for a file
src/toolkit/query_cache.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/query_cache.cpp.s
.PHONY : src/toolkit/query_cache.cpp.s

src/toolkit/utils.o: src/toolkit/utils.cpp.o
.PHONY : src/toolkit/utils.o

# target to build an object file
src/toolkit/utils.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/utils.cpp.o
.PHONY : src/toolkit/utils.cpp.o

src/toolkit/utils.i: src/toolkit/utils.cpp.i
.PHONY : src/toolkit/utils.i

# target to preprocess a source file
src/toolkit/utils.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/utils.cpp.i
.PHONY : src/toolkit/utils.cpp.i

src/toolkit/utils.s: src/toolkit/utils.cpp.s
.PHONY : src/toolkit/utils.s

# target to generate assembly for a file
src/toolkit/utils.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/utils.cpp.s
.PHONY : src/toolkit/utils.cpp.s

src/toolkit/z3cache.o: src/toolkit/z3cache.cpp.o
.PHONY : src/toolkit/z3cache.o

# target to build an object file
src/toolkit/z3cache.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/z3cache.cpp.o
.PHONY : src/toolkit/z3cache.cpp.o

src/toolkit/z3cache.i: src/toolkit/z3cache.cpp.i
.PHONY : src/toolkit/z3cache.i

# target to preprocess a source file
src/toolkit/z3cache.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/z3cache.cpp.i
.PHONY : src/toolkit/z3cache.cpp.i

src/toolkit/z3cache.s: src/toolkit/z3cache.cpp.s
.PHONY : src/toolkit/z3cache.s

# target to generate assembly for a file
src/toolkit/z3cache.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/src/toolkit/z3cache.cpp.s
.PHONY : src/toolkit/z3cache.cpp.s

tokens.o: tokens.cpp.o
.PHONY : tokens.o

# target to build an object file
tokens.cpp.o:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/tokens.cpp.o
.PHONY : tokens.cpp.o

tokens.i: tokens.cpp.i
.PHONY : tokens.i

# target to preprocess a source file
tokens.cpp.i:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/tokens.cpp.i
.PHONY : tokens.cpp.i

tokens.s: tokens.cpp.s
.PHONY : tokens.s

# target to generate assembly for a file
tokens.cpp.s:
	$(MAKE) -f CMakeFiles/symdivine.dir/build.make CMakeFiles/symdivine.dir/tokens.cpp.s
.PHONY : tokens.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... symdivine"
	@echo "... libs/docopt/docopt.o"
	@echo "... libs/docopt/docopt.i"
	@echo "... libs/docopt/docopt.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... src/llvmsym/datastore.o"
	@echo "... src/llvmsym/datastore.i"
	@echo "... src/llvmsym/datastore.s"
	@echo "... src/llvmsym/emptydatastore.o"
	@echo "... src/llvmsym/emptydatastore.i"
	@echo "... src/llvmsym/emptydatastore.s"
	@echo "... src/llvmsym/error.o"
	@echo "... src/llvmsym/error.i"
	@echo "... src/llvmsym/error.s"
	@echo "... src/llvmsym/formula/rpn.o"
	@echo "... src/llvmsym/formula/rpn.i"
	@echo "... src/llvmsym/formula/rpn.s"
	@echo "... src/llvmsym/formula/z3.o"
	@echo "... src/llvmsym/formula/z3.i"
	@echo "... src/llvmsym/formula/z3.s"
	@echo "... src/llvmsym/llvmdata.o"
	@echo "... src/llvmsym/llvmdata.i"
	@echo "... src/llvmsym/llvmdata.s"
	@echo "... src/llvmsym/memorylayout.o"
	@echo "... src/llvmsym/memorylayout.i"
	@echo "... src/llvmsym/memorylayout.s"
	@echo "... src/llvmsym/programutils/config.o"
	@echo "... src/llvmsym/programutils/config.i"
	@echo "... src/llvmsym/programutils/config.s"
	@echo "... src/llvmsym/programutils/statistics.o"
	@echo "... src/llvmsym/programutils/statistics.i"
	@echo "... src/llvmsym/programutils/statistics.s"
	@echo "... src/llvmsym/smtdatastore.o"
	@echo "... src/llvmsym/smtdatastore.i"
	@echo "... src/llvmsym/smtdatastore.s"
	@echo "... src/llvmsym/smtdatastore_partial.o"
	@echo "... src/llvmsym/smtdatastore_partial.i"
	@echo "... src/llvmsym/smtdatastore_partial.s"
	@echo "... src/llvmsym/stanalysis/inputvariables.o"
	@echo "... src/llvmsym/stanalysis/inputvariables.i"
	@echo "... src/llvmsym/stanalysis/inputvariables.s"
	@echo "... src/llvmsym/thread.o"
	@echo "... src/llvmsym/thread.i"
	@echo "... src/llvmsym/thread.s"
	@echo "... src/symdivine.o"
	@echo "... src/symdivine.i"
	@echo "... src/symdivine.s"
	@echo "... src/toolkit/ltl2ba.o"
	@echo "... src/toolkit/ltl2ba.i"
	@echo "... src/toolkit/ltl2ba.s"
	@echo "... src/toolkit/query_cache.o"
	@echo "... src/toolkit/query_cache.i"
	@echo "... src/toolkit/query_cache.s"
	@echo "... src/toolkit/utils.o"
	@echo "... src/toolkit/utils.i"
	@echo "... src/toolkit/utils.s"
	@echo "... src/toolkit/z3cache.o"
	@echo "... src/toolkit/z3cache.i"
	@echo "... src/toolkit/z3cache.s"
	@echo "... tokens.o"
	@echo "... tokens.i"
	@echo "... tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

